language: cpp
sudo: required
dist: trusty
#group: wtf

# Travis CI VM OSs -> 2 OSs
os:
    - linux
    - osx

# Travis CI build matrix components -> 2 compilers
compiler:
    - gcc
    - clang

# Travis CI environmental variables -> 2 env variables
env:
    global:
    - TRAVIS_BUILD_TYPE=Debug
    - TRAVIS_BUILD_TYPE=Release
  # Coverity
    # COVERITY_SCAN_TOKEN
    # ** specific to your project **
    - secure: "...."
    - COVERITY_SCAN_BUILD_COMMAND="make -j2"
    - COVERITY_SCAN_PROJECT_NAME="doevelopper/cppbdd101"
    - COVERITY_SCAN_NOTIFICATION_EMAIL="happyman@hotmail.fr"
    - COVERITY_SCAN_BRANCH_PATTERN="master"
    - COVERITY_SCAN_BUILD_URL="https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh"
    - COVERITY_SCAN_BUILD="curl -s $COVERITY_SCAN_BUILD_URL | bash"

git:
    depth: 3

stages:
  - "build only"
  - test

# blocklist
branches:
    except:
        - legacy
        - experimental
 # safelist 
branches:
    only:
        - master
        - develop
        - coverity_scan
    except:
        - gh-page

addons:
    coverity_scan:
        project:
            name: "doevelopper/cppbdd101"
            description: "Build submitted via Travis CI"
        notification_email: {NOTIFICATION_EMAIL}
        build_command_prepend: "(rm -rf $TRAVIS_BUILD_DIR/build ; mkdir $TRAVIS_BUILD_DIR/build ; cd $TRAVIS_BUILD_DIR/build ; cmake -DCMAKE_BUILD_TYPE=Release $TRAVIS_BUILD_DIR)"
        build_command:   "make -C $TRAVIS_BUILD_DIR/build"
        branch_pattern: coverity_scan
    artifacts:
        paths:
            - "cppbdd.zip"
        key:
            secure: ....
        secret:
            secure: ....
        bucket: cppbdd101-travis
        region: us-east-1
        endpoint: artifactory.local
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - gcc-7
            - g++-7
            - clang-5.0
            - automake cmake autoconf libtool libssl-dev graphviz mscgen
            - libconfig-dev
            - libpcap-dev
            - binutils
            - cabextract
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils
        coverity_scan:
            project:
                #name: "$TRAVIS_REPO_SLUG"
                name: doevelopper/cppbdd101
                notification_email: happyman@hotmail.fr
                description: "Cpp BDD 101 Build submitted via Travis CI"
                    # Commands to prepare for build_command
                    # ** likely specific to your build **
                    #build_command_prepend: "./bootstrap && ./configure --enable-test-cpp --enable-test-vald --enable-test-helper --enable-test-perf --enable-user-guides --enable-test-perf-proc --enable-test-example"
                build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8&& ./autogen.sh && ./configure && make clean"
                    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
                    # ** likely specific to your build **
                build_command:   "make VERBOSE=1 -j4"
                branch_pattern: coverity_scan

before_deploy:

deploy:
    provider: bintray
    api_key:
        secure: ....
    file: "Cppbdd101.zip"
    skip_cleanup: true
    on:
        tags: true
        condition: $CAN_DEPLOY = True && $TRAVIS_OS_NAME = Linux #$BUILDTYPE = Release
        all_branches: true
        repo: doevelopper/cppbdd101

after_deploy:

cache:
    ccache: true
    pip: true
    apt: true
    directories:
        - $HOME/.m2
        - $HOME/cppbdd-install
        - $HOME/cppbdd-doxygen-install
env:
    global:
        #
        # By default Linaro CODECOV_TOKEN token is used. It's ok to use it to see
        # for individual commit validation. But you you want to track tests history
        # you need generated new one at https://codecov.io specific for your repo.
        - CODECOV_TOKEN=a733c34c-5f5c-4ff1-af4b-e9f5edb1ab5e
        - DPDK_VERS="17.08"
        - MAVEN_OPTS="-Xmx512m"
        - JAVA_OPTS="-Xmx512m"
    matrix:
        - CONF=""
        - CONF="--disable-abi-compat"
        - CONF="--enable-deprecated"
        - CONF="--enable-dpdk-zero-copy"
        - CONF="--disable-static-applications"
        - CONF="--disable-host-optimization"
        - CONF="--disable-host-optimization --disable-abi-compat"
        - DPDK_SHARED="y" CONF="--disable-static-applications"
        - DPDK_VERS="17.11" CONF=""
        - DPDK_VERS="17.11" DPDK_SHARED="y" CONF="--disable-static-applications"

before_script:
    - uname -a
    # to stop the script after an error/warning
    - set -e
    - |-
        case "${BUILD_TYPE}" in
            "coverage")
                cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DBUILD_COVERAGE=ON ..
            ;;
            "asan")
                cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DENABLE_SANITIZER=address ..
            ;;
            "ubsan")
                cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DENABLE_SANITIZER=undefined ..
            ;;
            "cross")
                cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw64.cmake -DCMAKE_EXE_LINKER_FLAGS="-static -s" ..
            ;;
            "release")
                cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
            ;;
            *)
                # Run CMake
                - mkdir build
                - cd build
                - cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} ..
            ;;
        esac

before_install:
    #- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    # Update package managers
    - sudo apt-get update -qq
    - sudo apt-get install -qq build-essential git-core lcov ggcov 
    - sudo apt-get install libboost-all-dev
    - sudo apt-get update && sudo apt-get install build-essential software-properties-common -y && sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install gcc-snapshot -y
    - sudo apt-get install gcc-6 g++-6 -y 
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; sudo apt-get install -y -qq lcov curl; fi
    - curl https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.tar.gz  | sudo tar -x -z --strip-components 1 -C /usr
    #- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update;  sudo apt-get install -qq --force-yes libgd2-xpm   fi
    #- if [ `uname -m` = x86_64 ]; then sudo dpkg --add-architecture i386; sudo apt-get update -qq; sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update;              fi

    # Use ccache also for clang and clang++ on linux
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CC" == "clang" ];    then sudo ln -s ../../bin/ccache /usr/lib/ccache/clang;   fi; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CC" == "clang" ];    then export CFLAGS="-Qunused-arguments";                  fi; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "clang++" ]; then sudo ln -s ../../bin/ccache /usr/lib/ccache/clang++; fi; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" == "clang++" ]; then export CXXFLAGS="-Qunused-arguments";                fi; fi

    # Install ccache on osx
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ccache;                               fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH="/usr/local/opt/ccache/libexec:$PATH"; fi

    # Print some more system information after installing all build tools
    - echo "-------------------- BEGIN SYSTEM INFORMATION --------------------"
    - uname -a
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then lsb_release -a;                     fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];   then system_profiler SPSoftwareDataType; fi
    - env
    - which cmake
    - cmake --version
    - which $CC
    - $CC --version
    - which $CXX
    - $CXX --version
    - which ccache
    - ccache --version
    - ccache -s
    - echo "--------------------  END SYSTEM INFORMATION  --------------------"

before_script:

script:
    -   if [[ "${COVERITY_SCAN_BRANCH}" == 1 ]];
            then
                echo "Don't build on coverty_scan branch.";
                exit 0;
        fi
    - make VERBOSE=1
    #- make test
    - ctest --verbose
#    - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then make ; fi
#    - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then mkdir build && cd build && travis_wait 60 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../product $CMAKECMD_ARGS ../ ; fi
#    - if [ -f CMakeCache.txt ]; then make -j4 ; fi
    - wget https://dl.bintray.com/jfrog/jfrog-cli-go/1.14.0/jfrog-cli-linux-amd64/jfrog
    - chmod +x jfrog
    - mvn clean install
    - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD
    - ./jfrog rt u "multi*/*.jar" travisci-generic-local --build-name=travisci-generic-artifactory --build-number=$TRAVIS_BUILD_NUMBER --flat=false
    - ./jfrog rt u "multi*/*.war" travisci-generic-local --build-name=travisci-generic-artifactory --build-number=$TRAVIS_BUILD_NUMBER --flat=false
    - ./jfrog rt bce travisci-generic-artifactory $TRAVIS_BUILD_NUMBER
    - ./jfrog rt bp travisci-generic-artifactory $TRAVIS_BUILD_NUMBER

after_script:

after_failure:
  - cat config.log
  - find . -name "*.trs" | xargs grep -l '^.test-result. FAIL' | while read trs ; do echo FAILURE detected at $trs; cat ${trs%%.trs}.log ; done

after_success:
  - |
    if [[ "${BUILD_TYPE}" == "Coverage" ]]; then
        bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
    fi

notifications:
    email:
        recipients:
            - happyman@hotmail.fr
            - rolland.doe@gmail.com
        on_success: always  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: always    # default: false

before_install:

install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
    - |
        if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
            echo ""
        elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
            echo ""
        fi